source 'https://github.com/CocoaPods/Specs.git' # 官方库
project 'Runner.xcodeproj'

platform :ios, '15.0'
use_frameworks!

workspace 'Runner.xcworkspace'


target 'Runner' do
  # 网络请求
  pod 'Moya', '~> 15.0'
  
  # 布局约束
  pod 'SnapKit', '~> 5.7.1'
  
  # 键盘管理
  pod 'IQKeyboardManagerSwift', '~> 6.5.16'
  
  # 图片加载
  pod 'Kingfisher', '~> 7.10.1'
  
  # JSON处理
  pod 'SwiftyJSON', '~> 5.0'
  
  # 本地存储
  pod 'KeychainAccess', '~> 4.2'
  
  pod 'MJRefresh', '~> 3.7.9'

  pod 'ProgressHUD', '~> 14.1.1'


end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end 
