source 'https://github.com/CocoaPods/Specs.git' # 官方库
project 'Runner.xcodeproj'

platform :ios, '13.0'
use_frameworks!

workspace 'Runner.xcworkspace'


target 'Runner' do
  
  pod 'Masonry', '1.1.0'
  pod 'MMLayout', '0.2.0'
  pod 'MJRefresh', '3.7.9'
  pod 'DZNEmptyDataSet', '1.8.1'
  pod 'TPKeyboardAvoiding', '1.3.5'
  pod 'JXCategoryView', '1.5.2'
  pod 'AFNetworking', '~> 4.0.1'
  pod 'JSONModel', '~> 1.8.0'
  pod 'Reachability', '3.7.6'
  pod 'SDWebImage', '5.19.1'
  pod 'JDStatusBarNotification', :git => 'https://github.com/kerain/JDStatusBarNotification.git'
  pod 'MBProgressHUD',:git => 'https://github.com/jdg/MBProgressHUD.git', :commit => '18c442d57398cee5ef57f852df10fc5ff65f0763'
  pod 'lottie-ios', '~>  2.5.3'
  pod 'SVGAPlayer', '2.3.4'
  pod 'QGVAPlayer', '1.0.16'
  pod 'FLAnimatedImage', '1.0.12'
  pod 'JHChainableAnimations', '3.0.1'
  pod 'pop', '1.0.12'
  pod 'Ono', :git => 'https://github.com/kerain/Ono.git'
  pod 'WCDB', '~> 1.0.7.5'
  pod 'WCDBOptimizedSQLCipher', '1.2.1'
  pod 'ReactiveObjC', '3.1.0'
  pod 'SocketRocket', '0.5.1'
  pod 'SSZipArchive', '2.2.2'
  pod 'AvoidCrash', '2.5.2'
  pod 'StreamingKit', '~> 0.1.30'
  
  
  # 网络请求
  pod 'Moya', '~> 15.0'
  
  # 布局约束
  pod 'SnapKit', '~> 5.7.1'
  
  # 本地存储
  pod 'KeychainAccess', '~> 4.2'
  
  pod 'MJRefresh', '~> 3.7.9'

  pod 'ProgressHUD', '~> 14.1.1'

  pod 'TXUpload', :path => 'LeanTouchPod/TXUpload'  # 腾讯短视频UGC && 腾讯COS
  pod 'YYKit',    :path => 'LeanTouchPod/YYKit'  # YYKit
  pod 'STBeauty', :path => 'LeanTouchPod/STBeauty'  # STBeauty
  
  # 键盘管理
  pod 'IQKeyboardManagerSwift', '~> 6.5.16'
  
  # 图片加载
  pod 'Kingfisher', '~> 7.10.1'
  
  # JSON处理
  pod 'SwiftyJSON', '~> 5.0'
  
  # 本地存储
  pod 'KeychainAccess', '~> 4.2'
  
  pod 'MJRefresh', '~> 3.7.9'

  pod 'ProgressHUD', '~> 14.1.1'

  pod 'JVerification', '~> 3.2.1'
  pod 'JPush', '~> 4.6.4'
  pod 'HCHollyOC', '~> 0.9.6'
  pod 'Bugly', '~> 2.6.1'
  pod 'UMCCommon', '7.1.3'
  pod 'TXIMSDK_Plus_iOS_Bitcode', '5.8.1672'
  pod 'TXLiteAVSDK_Professional', '~> 11.4.14445'
  pod 'GT3Captcha-iOS', '0.15.2'
  pod 'BDASignalSDK', '1.0.3'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
  # Bitcode 处理
    bitcode_strip_path = `xcrun --find bitcode_strip`.chop!
    def strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
      framework_path = File.join(Dir.pwd, framework_relative_path)
      command = "#{bitcode_strip_path} #{framework_path} -r -o #{framework_path}"
      puts "Stripping bitcode: #{command}"
      system(command)
    end
    framework_paths = [
      "/Pods/TXIMSDK_Plus_iOS_Bitcode/ImSDK_Plus.framework/ImSDK_Plus",
    ]
    framework_paths.each do |framework_relative_path|
      strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
    end

end
